version : '3'
services:
  database:
    container_name: postgres-csc2022
    image : postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - C:\Users\USER\Documents\data\postgres:/data/postgres
    env_file:
      - csc202.env